### PR TITLE
Check if nodes actually exist in EC2 and include status in output

### PR DESCRIPTION
**Pull request by eherot**
Only runs if aws_access_key_id knife option is detected so as not to create a dependency on EC2.

(PS. My editor also removed a bunch of trailing spaces ;-))

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
:+1:

**Comment by paulmooring** [comment]
I like the idea, but it's not uncommon to have ec2 config in knife.rb and not have all your nodes in ec2.  This should probably be a command line option to turn on.

**Comment by eherot** [comment]
Ask and yee shall receive!

**Comment by paulmooring** [comment]
1.2.0 has been pushed to RubyGems with this fix, thanks @eherot

**Comment by eherot** [comment]
Thank you guys!

**Pull request merged**
